export default [
  {
    'id': 1,
    'text': '单选题单选题单选题单选题单选题',
    'min': 0, // 整数值，默认0，最少选项数量,主要用于多选题和排序题,
    'max': 2, // 整数值，默认0，最多选项数量,主要用于多选题和排序题,
    'kind': 1, // "试题类型1单选2多选3判断题4填空题5排序题",
    'order': 1, // 整数值，试题序号从1开始,
    'remark': '单选题',
    'options': [
      { // --填空题为空，其它题有内容 {
        'id': 11, // "选项id",
        'text': '第一个选项', // "选项内容",
        'jump': 0, // 跳转试题序号，0不跳转,
        'mute': 2, // 是否互斥1互斥2非互斥
        'order': 1, // 选项序号从1开始,
      },
      { // --填空题为空，其它题有内容 {
        'id': 12, // "选项id",
        'text': '第二个选项', // "选项内容",
        'jump': 0, // 跳转试题序号，0不跳转,
        'mute': 2, // 是否互斥1互斥2非互斥
        'order': 2, // 选项序号从1开始,
      },
      { // --填空题为空，其它题有内容 {
        'id': 13, // "选项id",
        'text': '第三个选项，跳转第三题', // "选项内容",
        'jump': 3, // 跳转试题序号，0不跳转,
        'mute': 2, // 是否互斥1互斥2非互斥
        'order': 3, // 选项序号从1开始,
        // 'regulars': { // --有可能为空
        //   'kind': '规则类型1字符串2整数3浮点数4日期',
        //   'maxval': '最大值，用于整数、浮点数、日期类型',
        //   'minval': '最小值，用于整数、浮点数、日期类型,',
        // },
      },
      { // --填空题为空，其它题有内容 {
        'id': 14, // "选项id",
        'text': '其他{}', // "选项内容",
        'jump': 0, // 跳转试题序号，0不跳转,
        'mute': 2, // 是否互斥1互斥2非互斥
        'order': 4, // 选项序号从1开始,
        'regulars': { // --有可能为空
          'kind': '规则类型1字符串2整数3浮点数4日期',
          'maxval': '最大值，用于整数、浮点数、日期类型',
          'minval': '最小值，用于整数、浮点数、日期类型,',
        },
      },
    ],
    // 'regulars': {
    //   'kind': '规则类型1字符串2整数3浮点数4日期',
    //   'maxval': '最大值，用于整数、浮点数、日期类型',
    //   'minval': '最小值，用于整数、浮点数、日期类型,',
    // },
  },
  {
    'id': 2,
    'text': '多选多选多选多选多选',
    'min': 0, // 整数值，默认0，最少选项数量,主要用于多选题和排序题,
    'max': 2, // 整数值，默认0，最多选项数量,主要用于多选题和排序题,
    'kind': 2, // "试题类型1单选2多选3判断题4填空题5排序题",
    'order': 2, // 整数值，试题序号从1开始,
    'remark': '多选',
    'options': [
      { // --填空题为空，其它题有内容 {
        'id': 21, // "选项id",
        'text': '第一个选项', // "选项内容",
        'jump': 0, // 跳转试题序号，0不跳转,
        'mute': 2, // 是否互斥1互斥2非互斥
        'order': 1, // 选项序号从1开始,
      },
      { // --填空题为空，其它题有内容 {
        'id': 22, // "选项id",
        'text': '第二个选项，跳转到第四题', // "选项内容",
        'jump': 4, // 跳转试题序号，0不跳转,
        'mute': 2, // 是否互斥1互斥2非互斥
        'order': 2, // 选项序号从1开始,
      },
      { // --填空题为空，其它题有内容 {
        'id': 23, // "选项id",
        'text': '第三个选项', // "选项内容",
        'jump': 0, // 跳转试题序号，0不跳转,
        'mute': 2, // 是否互斥1互斥2非互斥
        'order': 3, // 选项序号从1开始,
        // 'regulars': { // --有可能为空
        //   'kind': '规则类型1字符串2整数3浮点数4日期',
        //   'maxval': '最大值，用于整数、浮点数、日期类型',
        //   'minval': '最小值，用于整数、浮点数、日期类型,',
        // },
      },
      { // --填空题为空，其它题有内容 {
        'id': 24, // "选项id",
        'text': '其他{}，互斥哦', // "选项内容",
        'jump': 0, // 跳转试题序号，0不跳转,
        'mute': 1, // 是否互斥1互斥2非互斥
        'order': 4, // 选项序号从1开始,
        'regulars': { // --有可能为空
          'kind': '规则类型1字符串2整数3浮点数4日期',
          'maxval': '最大值，用于整数、浮点数、日期类型',
          'minval': '最小值，用于整数、浮点数、日期类型,',
        },
      },
    ],
    // 'regulars': {
    //   'kind': '规则类型1字符串2整数3浮点数4日期',
    //   'maxval': '最大值，用于整数、浮点数、日期类型',
    //   'minval': '最小值，用于整数、浮点数、日期类型,',
    // },
  },
  {
    'id': 3,
    'text': '判断题判断题判断题判断题判断题',
    'min': 0, // 整数值，默认0，最少选项数量,主要用于多选题和排序题,
    'max': 0, // 整数值，默认0，最多选项数量,主要用于多选题和排序题,
    'kind': 3, // "试题类型1单选2多选3判断题4填空题5排序题",
    'order': 3, // 整数值，试题序号从1开始,
    'remark': '判断题',
    'options': [
      { // --填空题为空，其它题有内容 {
        'id': 31, // "选项id",
        'text': '第一个选项{}', // "选项内容",
        'jump': 0, // 跳转试题序号，0不跳转,
        'mute': 2, // 是否互斥1互斥2非互斥
        'order': 1, // 选项序号从1开始,
        'regulars': { // --有可能为空
          'kind': '规则类型1字符串2整数3浮点数4日期',
          'maxval': '最大值，用于整数、浮点数、日期类型',
          'minval': '最小值，用于整数、浮点数、日期类型,',
        },
      },
      { // --填空题为空，其它题有内容 {
        'id': 32, // "选项id",
        'text': '第二个选项，跳转到第五条', // "选项内容",
        'jump': 5, // 跳转试题序号，0不跳转,
        'mute': 2, // 是否互斥1互斥2非互斥
        'order': 2, // 选项序号从1开始,
      },
    ],
    // 'regulars': {
    //   'kind': '规则类型1字符串2整数3浮点数4日期',
    //   'maxval': '最大值，用于整数、浮点数、日期类型',
    //   'minval': '最小值，用于整数、浮点数、日期类型,',
    // },
  },
  {
    'id': 4,
    'text': '填空題填空題填空題填空題填空題',
    'min': 0, // 整数值，默认0，最少选项数量,主要用于多选题和排序题,
    'max': 0, // 整数值，默认0，最多选项数量,主要用于多选题和排序题,
    'kind': 4, // "试题类型1单选2多选3判断题4填空题5排序题",
    'order': 4, // 整数值，试题序号从1开始,
    'remark': '填空題',
    'options': [
    ],
    'regulars': {
      'kind': 1, // '规则类型1字符串2整数3浮点数4日期',
      'maxval': 0, // '最大值，用于整数、浮点数、日期类型',
      'minval': 0, // '最小值，用于整数、浮点数、日期类型,',
    },
  },

  {
    'id': 5,
    'text': '排序题排序题排序题排序题排序题',
    'min': 0, // 整数值，默认0，最少选项数量,主要用于多选题和排序题,
    'max': 2, // 整数值，默认0，最多选项数量,主要用于多选题和排序题,
    'kind': 5, // "试题类型1单选2多选3判断题4填空题5排序题",
    'order': 5, // 整数值，试题序号从1开始,
    'remark': '排序题',
    'options': [
      { // --填空题为空，其它题有内容 {
        'id': 51, // "选项id",
        'text': '第一个选项', // "选项内容",
        'jump': 0, // 跳转试题序号，0不跳转,
        'mute': 2, // 是否互斥1互斥2非互斥
        'order': 1, // 选项序号从1开始,
      },
      { // --填空题为空，其它题有内容 {
        'id': 52, // "选项id",
        'text': '第二个选项', // "选项内容",
        'jump': 0, // 跳转试题序号，0不跳转,
        'mute': 2, // 是否互斥1互斥2非互斥
        'order': 2, // 选项序号从1开始,
      },
      { // --填空题为空，其它题有内容 {
        'id': 53, // "选项id",
        'text': '第三个选项', // "选项内容",
        'jump': 0, // 跳转试题序号，0不跳转,
        'mute': 2, // 是否互斥1互斥2非互斥
        'order': 3, // 选项序号从1开始,
        // 'regulars': { // --有可能为空
        //   'kind': '规则类型1字符串2整数3浮点数4日期',
        //   'maxval': '最大值，用于整数、浮点数、日期类型',
        //   'minval': '最小值，用于整数、浮点数、日期类型,',
        // },
      },
      { // --填空题为空，其它题有内容 {
        'id': 54, // "选项id",
        'text': '其他{}', // "选项内容",
        'jump': 0, // 跳转试题序号，0不跳转,
        'mute': 2, // 是否互斥1互斥2非互斥
        'order': 4, // 选项序号从1开始,
        'regulars': { // --有可能为空
          'kind': '规则类型1字符串2整数3浮点数4日期',
          'maxval': '最大值，用于整数、浮点数、日期类型',
          'minval': '最小值，用于整数、浮点数、日期类型,',
        },
      },
    ],
    // 'regulars': {
    //   'kind': '规则类型1字符串2整数3浮点数4日期',
    //   'maxval': '最大值，用于整数、浮点数、日期类型',
    //   'minval': '最小值，用于整数、浮点数、日期类型,',
    // },
  },
]

export const realData1 = {
  'msg': '操作成功',
  'code': 0,
  'data': [
    {
      'id': '9bd61e10f2fa4f438c51a6496a8fd742',
      'text': 'A01. 预防流感最好的办法是服用抗生素（消炎药）',
      'min': 0,
      'max': 0,
      'kind': '3',
      'code': 'A01',
      'order': 1,
      'remark': null,
      'options': [
        {
          'id': '1833d32e1e9a43c09e8bc11ee6ed5b16',
          'text': '正确',
          'jump': 0,
          'order': 1,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'a8e09a18f2634143aaf155fa12074b1c',
          'text': '错误',
          'jump': 0,
          'order': 2,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
      ],
      'regulars': null,
    },
    {
      'id': '4ac7f5a48e6e48079f4ddc69b253c7f9',
      'text': 'A02. 保健食品不是药品，也不能代替药品治病。',
      'min': 0,
      'max': 0,
      'kind': '3',
      'code': 'A02',
      'order': 2,
      'remark': null,
      'options': [
        {
          'id': '8db6dfb043f640ce95fbc97f4e9378b5',
          'text': '正确',
          'jump': 0,
          'order': 1,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'efbf9b9def584442af27dc528a125dd9',
          'text': '错误',
          'jump': 0,
          'order': 2,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
      ],
      'regulars': null,
    },
    {
      'id': '97aa28d8b55c46ef94765799ad232b94',
      'text': 'A03. 输液（打吊针）疗效好、作用快，所以有病后要首先选择输液。',
      'min': 0,
      'max': 0,
      'kind': '3',
      'code': 'A03',
      'order': 3,
      'remark': null,
      'options': [
        {
          'id': 'adb774a3af244a3d9763a6c3e94557d7',
          'text': '正确',
          'jump': 0,
          'order': 1,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'c79dce1b4021418dbb79741a8f7beebd',
          'text': '错误',
          'jump': 0,
          'order': 2,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
      ],
      'regulars': null,
    },
    {
      'id': 'c2ac1ab724634ae99287d7d4660226ab',
      'text': 'A04. 水果和蔬菜的营养成份相近，可以用吃水果代替吃蔬菜。',
      'min': 0,
      'max': 0,
      'kind': '3',
      'code': 'A04',
      'order': 4,
      'remark': null,
      'options': [
        {
          'id': '084ca95ce5cf472a98b45c7fedcc50c8',
          'text': '正确',
          'jump': 0,
          'order': 1,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '74103714a23d4d24bdea3f3cfec47e74',
          'text': '错误',
          'jump': 0,
          'order': 2,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
      ],
      'regulars': null,
    },
    {
      'id': '0edcd7cdcf84420ba996b02cd28353a3',
      'text': 'A011.有中医药健康文化知识的宣传栏（宣传墙）',
      'min': 0,
      'max': 0,
      'kind': '1',
      'code': 'A011',
      'order': 5,
      'remark': null,
      'options': [
        {
          'id': '0540b6d465e6424b93f22842fc80c509',
          'text': '①是',
          'jump': 0,
          'order': 1,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '57d8f7bed2b94231b0d7764dea6fa89a',
          'text': '②否',
          'jump': 0,
          'order': 2,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '37842666ede249b5bb591ae8d8b3f0df',
          'text': '③不知道',
          'jump': 0,
          'order': 3,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
      ],
      'regulars': null,
    },
    {
      'id': '82ded13925dd4722973a32364bc2e7c2',
      'text': 'A012.发放过宣传中医药健康文化知识的印刷材料',
      'min': 0,
      'max': 0,
      'kind': '1',
      'code': 'A012',
      'order': 6,
      'remark': null,
      'options': [
        {
          'id': 'da38ae31cb2f4a8eb5f3cb8cc0ad7dd3',
          'text': '①是',
          'jump': 0,
          'order': 1,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '7016c7ffb18b44bca0ddbc6dc8997738',
          'text': '②否',
          'jump': 0,
          'order': 2,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'baf4ab5d1fff4db3a43d3f8a1167719f',
          'text': '③不知道',
          'jump': 0,
          'order': 3,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
      ],
      'regulars': null,
    },
    {
      'id': 'c66aee11b5ca49428e0cc5b9c4e92119',
      'text': 'A013.播放过宣传中医药健康文化知识的音像材料',
      'min': 0,
      'max': 0,
      'kind': '1',
      'code': 'A013',
      'order': 7,
      'remark': null,
      'options': [
        {
          'id': '16ba3c077b38424ca85b90f97ba7219d',
          'text': '①是',
          'jump': 0,
          'order': 1,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '8d3c284514744b26a989fc96cfde0723',
          'text': '②否',
          'jump': 0,
          'order': 2,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '9bfdf1c6fa8a4e0e8efee39a9fd3408b',
          'text': '③不知道',
          'jump': 0,
          'order': 3,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
      ],
      'regulars': null,
    },
    {
      'id': '75647fc6a62a4121ba624c7d9bd466a7',
      'text': 'A014.组织过义诊、讲座等宣传中医药健康文化知识的活动',
      'min': 0,
      'max': 0,
      'kind': '1',
      'code': 'A014',
      'order': 8,
      'remark': null,
      'options': [
        {
          'id': '8b2eb52fa2f64a6480dbe9703c45a2ed',
          'text': '①是',
          'jump': 0,
          'order': 1,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '3c9c069e63174798a94318b468cf8c62',
          'text': '②否',
          'jump': 0,
          'order': 2,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'e1fe35fdf40e41c2adb8e4b49285584b',
          'text': '③不知道',
          'jump': 0,
          'order': 3,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
      ],
      'regulars': null,
    },
    {
      'id': '45fba549194045f0bfbf48f973abc5c6',
      'text': 'B01. 关于健康的概念，描述完整的是：',
      'min': 0,
      'max': 0,
      'kind': '1',
      'code': 'B01',
      'order': 9,
      'remark': null,
      'options': [
        {
          'id': 'c0848c2fddf64c87b24164d136cad582',
          'text': '① 健康就是体格强壮，没有疾病',
          'jump': 0,
          'order': 1,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '6b6aa6cf4f3143df90f1979b8dfc6890',
          'text': '② 健康就是心理素质好，体格强壮',
          'jump': 0,
          'order': 2,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'b49198dd10854c1aa08913ec553108d5',
          'text': '③ 健康不仅是没有疾病，而是身体、心理和社会适应的完好状态',
          'jump': 0,
          'order': 3,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '259c3239e536466e8c9ed14328b54d8e',
          'text': '④ 不知道',
          'jump': 0,
          'order': 4,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
      ],
      'regulars': null,
    },
    {
      'id': '58963a7d3f4347c38420b422cbf71c0b',
      'text': 'B02. 通常情况下，献血者要到______进行无偿献血。',
      'min': 0,
      'max': 0,
      'kind': '1',
      'code': 'B02',
      'order': 10,
      'remark': null,
      'options': [
        {
          'id': 'a0ad036ed89a4d13b910459924834da9',
          'text': '① 医院 ',
          'jump': 0,
          'order': 1,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '558329d7005146db80b4f869da3683f7',
          'text': '② 血液中心（血站）或其献血车',
          'jump': 0,
          'order': 2,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '7546e006c6d9433e900c947ee2e12661',
          'text': '③ 疾病预防控制中心',
          'jump': 0,
          'order': 3,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'e3590a19a9034a49a880812194b5f24f',
          'text': '④ 不知道',
          'jump': 0,
          'order': 4,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
      ],
      'regulars': null,
    },
    {
      'id': '70bfae0b9a17457f805ee3aad8349f5e',
      'text': 'B03. 乙肝可以通过以下哪些方式传染给他人？',
      'min': 0,
      'max': 0,
      'kind': '1',
      'code': 'B03',
      'order': 11,
      'remark': null,
      'options': [
        {
          'id': '3af4bf76e9034bada76d90623dc4e760',
          'text': '① 与病人或感染者一起工作、吃饭、游泳',
          'jump': 0,
          'order': 1,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '5bb88e5e701f445db4aaefa245129207',
          'text': '② 可以通过性行为、输血、母婴传播',
          'jump': 0,
          'order': 2,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '04dd3961fbed43f58115fb2287843ad6',
          'text': '③ 同病人或感染者说话、握手、拥抱',
          'jump': 0,
          'order': 3,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'bed9f3e144eb496cb6d520070afb3ad8',
          'text': '④ 不知道',
          'jump': 0,
          'order': 4,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
      ],
      'regulars': null,
    },
    {
      'id': '14028585249042b4b8c0766074a05ec6',
      'text': 'B04. 关于自测血压的说法，错误的是：',
      'min': 0,
      'max': 0,
      'kind': '1',
      'code': 'B04',
      'order': 12,
      'remark': null,
      'options': [
        {
          'id': '6f660243c9b8416db6fc5fc96d07a228',
          'text': '① 自测血压对高血压诊断有参考价值',
          'jump': 0,
          'order': 1,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '71138780a0054ce7a37b49814a5f1385',
          'text': '② 高血压患者定期自测血压，可为医生制定治疗方案和评价治疗效果提供依据',
          'jump': 0,
          'order': 2,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'c0b6b07a45604270abbf5c5637d7b0f0',
          'text': '③ 高血压患者只要自测血压稳定，就可以不用定期到门诊进行随访治疗了',
          'jump': 0,
          'order': 3,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '94a720722fb547819e9f9ac7d741d7c1',
          'text': '④ 不知道',
          'jump': 0,
          'order': 4,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
      ],
      'regulars': null,
    },
    {
      'id': 'ce9f7e60316b4b558ecd667512734a26',
      'text': 'C01. 关于促进心理健康的方法，以下说法正确的是：',
      'min': 2,
      'max': 4,
      'kind': '2',
      'code': 'C01',
      'order': 13,
      'remark': null,
      'options': [
        {
          'id': 'bd281a38f6df459f948de7c59fbfd981',
          'text': '① 生活态度要乐观 ',
          'jump': 0,
          'order': 1,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'e0a3bd4b8f5f4d83b6ac2e59a9c0fcd6',
          'text': '② 把目标定格在自己能力所及的范围内',
          'jump': 0,
          'order': 2,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '21d043d881bf4294a1e6af03f0370e78',
          'text': '③ 建立良好的人际关系，积极参加社会活动',
          'jump': 0,
          'order': 3,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '0016a36b79474773a004f00604d9adef',
          'text': '④ 通过吸烟、喝酒排解忧愁 ',
          'jump': 0,
          'order': 4,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'ecda464c4c0543dc97944e58bd799360',
          'text': ' ⑤ 不知道',
          'jump': 0,
          'order': 5,
          'mute': 1,
          'kind': '2',
          'regulars': null,
        },
      ],
      'regulars': null,
    },
    {
      'id': '5a6b80ea85a84e8eac7c208716047fea',
      'text': 'C02. 以下关于就医的说法，正确的是：',
      'min': 2,
      'max': 4,
      'kind': '2',
      'code': 'C02',
      'order': 14,
      'remark': null,
      'options': [
        {
          'id': '413bd34b1de94171a5f8610e3da5990a',
          'text': '① 不是所有的病都能够治愈',
          'jump': 0,
          'order': 1,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '7786606677554517b6eb39c3df8f1e01',
          'text': ' ② 治疗疾病是医生的事，与病人无关',
          'jump': 0,
          'order': 2,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'b3bf89594d614f268ef2b0276f26b62f',
          'text': '③ 医院就是治病的地方，治不好病就是医院的责任',
          'jump': 0,
          'order': 3,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '9c5d8db48fdd410487cd5b5d0aa6dc93',
          'text': '④ 生老病死是客观规律，需要理性看待诊疗结果 ',
          'jump': 0,
          'order': 4,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'a60a2c88763d4e2aa5c9409dc54ccb3a',
          'text': ' ⑤ 不知道',
          'jump': 0,
          'order': 5,
          'mute': 1,
          'kind': '2',
          'regulars': null,
        },
      ],
      'regulars': null,
    },
    {
      'id': '4c5ef135a271498289e40067ab1f5ba0',
      'text': 'C04. 孩子出现发热、皮疹等症状，家长应该：',
      'min': 2,
      'max': 4,
      'kind': '2',
      'code': 'C04',
      'order': 15,
      'remark': null,
      'options': [
        {
          'id': '0dbeec063ace466499510422355f6e9c',
          'text': '① 及时去医院就诊 ',
          'jump': 0,
          'order': 1,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '3b1d9902045f457a92fc61f921db100b',
          'text': '② 应暂停去幼儿园',
          'jump': 0,
          'order': 2,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '9546735da41743acbf037d59b6016b82',
          'text': '③ 及时通知孩子所在幼儿园的老师',
          'jump': 0,
          'order': 3,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'd70b5faf4478431eb60cc99ae6386eb1',
          'text': '④ 可以让孩子照常去幼儿园',
          'jump': 0,
          'order': 4,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '6c6660b93bd0417fbec0551119b2510f',
          'text': ' ⑤ 不知道',
          'jump': 0,
          'order': 5,
          'mute': 1,
          'kind': '2',
          'regulars': null,
        },
      ],
      'regulars': null,
    },
    {
      'id': '9d28642bcb3149c1a8f2256fdc129b44',
      'text': 'C05. 下面的说法，正确的有：',
      'min': 2,
      'max': 4,
      'kind': '2',
      'code': 'C05',
      'order': 16,
      'remark': null,
      'options': [
        {
          'id': '37b4e0d6ca594e3da38856aebc91be05',
          'text': '① 老年人治疗骨质疏松，为时已晚',
          'jump': 0,
          'order': 1,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'e8e62393562a480698854ace17a3eecb',
          'text': '② 骨质疏松是人衰老的正常生理现象',
          'jump': 0,
          'order': 2,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '94cd65b033024944bb1459314dd84d66',
          'text': '③ 中老年人饮奶可以减少骨质丢失',
          'jump': 0,
          'order': 3,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '12e0ee290f7042eb90fb0a81df55c81f',
          'text': '④ 多运动可以预防骨质疏松',
          'jump': 0,
          'order': 4,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'f55332d36a214dc088c667140943a0db',
          'text': ' ⑤ 不知道',
          'jump': 0,
          'order': 5,
          'mute': 1,
          'kind': '2',
          'regulars': null,
        },
      ],
      'regulars': null,
    },
    {
      'id': 'e2d75645694144abbed493252b0f1ac6',
      'text': 'D01. 李先生，45岁，身高170厘米，体重160斤（80公斤），他的BMI该怎样计算？（单选题）',
      'min': 0,
      'max': 0,
      'kind': '1',
      'code': 'D01',
      'order': 17,
      'remark': null,
      'options': [
        {
          'id': 'd902ad8ff9024cd88f13426615b78373',
          'text': '① (80)2 /170=37.6',
          'jump': 0,
          'order': 1,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'c6ff4ca644df470b8561edf971330447',
          'text': '② 80/(1.7)2 =27.7',
          'jump': 0,
          'order': 2,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '74901bb47b9f4211807d2df2890e7e10',
          'text': '③ 160/(1.7)2=55.4',
          'jump': 0,
          'order': 3,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'f397be579ccb4322a5bebbf74b7fdc46',
          'text': '④ 不知道',
          'jump': 0,
          'order': 4,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
      ],
      'regulars': null,
    },
    {
      'id': 'ea4bb6d721a54e28b5621c9e0c693b5b',
      'text': 'D02. 参照中国成年人体质指数的标准，李先生属于：（单选题）',
      'min': 0,
      'max': 0,
      'kind': '1',
      'code': 'D02',
      'order': 18,
      'remark': null,
      'options': [
        {
          'id': 'd65d47e6a17c4acfa1a62729947c7df6',
          'text': '① 肥胖',
          'jump': 0,
          'order': 1,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'b91f1eacc7d748368612c1de2c8cd8d7',
          'text': '② 体重正常',
          'jump': 0,
          'order': 2,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'a6f309bd9cb84170a04f1e973650b63e',
          'text': '③ 超重',
          'jump': 0,
          'order': 3,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '2ee2e6aa8d2146debd5f35c13b507dd9',
          'text': '④ 不知道',
          'jump': 0,
          'order': 4,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
      ],
      'regulars': null,
    },
    {
      'id': '3b30cd8d7e69404eb891c4eef5cf95d8',
      'text': 'E01. 您的身高是多少{}______（厘米）？\r\n',
      'min': 0,
      'max': 0,
      'kind': '4',
      'code': 'E01',
      'order': 19,
      'remark': null,
      'options': null,
      'regulars': [{'kind': '2',
        'maxval': '250',
        'minval': '20'}]},
    {
      'id': 'edbc4551bbd04e24a8e062c40559580b',
      'text': 'E02. 您的体重是多少{}______（公斤）？',
      'min': 0,
      'max': 0,
      'kind': '4',
      'code': 'E02',
      'order': 20,
      'remark': null,
      'options': null,
      'regulars': [{'kind': '2',
        'maxval': '230',
        'minval': '2'}]},
    {
      'id': '5c8813d198a14662b02d8714810732ae',
      'text': 'E03. 您现在吸烟吗？',
      'min': 0,
      'max': 0,
      'kind': '1',
      'code': 'E03',
      'order': 21,
      'remark': null,
      'options': [
        {
          'id': '2f29c7f54c934e78b781fb6cc87df26a',
          'text': '①每天吸，平均每天吸{}______ 支（注意：请按包/条数换算成支数。）',
          'jump': 0,
          'order': 1,
          'mute': 2,
          'kind': '1',
          'regulars': [{'kind': '2',
            'maxval': '50',
            'minval': '1'}]},
        {
          'id': '21a0a0ee575f480da4cf37f874e6e9a5',
          'text': '②吸，但不是每天。平均每周吸{}______支（注意：请按包/条数换算成支数。）',
          'jump': 0,
          'order': 2,
          'mute': 2,
          'kind': '1',
          'regulars': [{'kind': '2',
            'maxval': '300',
            'minval': '1'}]},
        {
          'id': 'd15d3118d2ef421d9adfd6ac593e4c08',
          'text': '③以前吸，但现在不吸',
          'jump': 0,
          'order': 3,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '4f1bf5bcdf2240178901b856e8bfc0af',
          'text': '④从不吸',
          'jump': 0,
          'order': 4,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
      ],
      'regulars': null,
    },
    {
      'id': '74988631caf8460a93190a968676fdb7',
      'text': 'E08. 您现在是否患有以下慢性病？（可多选）',
      'min': 1,
      'max': 6,
      'kind': '2',
      'code': 'E08',
      'order': 22,
      'remark': null,
      'options': [
        {
          'id': '6ca66806a1ac483daf039eb8991d5fd6',
          'text': '①没有患慢性病→跳至E17',
          'jump': 24,
          'order': 1,
          'mute': 1,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '987836f2bc6747c88cde1c3f2e4e7e5a',
          'text': '②高血压',
          'jump': 0,
          'order': 2,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '454e72bd394e43bf9cdfbe41f462fb3b',
          'text': ' ③心脏病',
          'jump': 0,
          'order': 3,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '79944cddc2d844e8b6469e403cfd89e9',
          'text': ' ④脑血管疾病（如中风、脑梗塞、脑血栓等）',
          'jump': 0,
          'order': 4,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '4e8963f6f5af43adbeb9c832cc5f9e70',
          'text': '⑤糖尿病',
          'jump': 0,
          'order': 5,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '98164e915ae34fea8a239f3828ca1732',
          'text': '⑥恶性肿瘤',
          'jump': 0,
          'order': 6,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '60875a55ab4c4f92924672df42cd6d77',
          'text': ' ⑦其他',
          'jump': 0,
          'order': 7,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
      ],
      'regulars': null,
    },
    {
      'id': '5e7f5693c4de410b8be846e7fb3cda93',
      'text': 'E09. 您第一次被医院确诊患慢性病，到现在有_____年。（不足1年，填“半年”）',
      'min': 0,
      'max': 0,
      'kind': '1',
      'code': 'E09',
      'order': 23,
      'remark': null,
      'options': [
        {
          'id': '8967ec2a40e04138b8ce4eb6d3a764cd',
          'text': '半年',
          'jump': 0,
          'order': 1,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'bc7e28381c08489985c8599a403fdaf7',
          'text': '{}_____年',
          'jump': 0,
          'order': 2,
          'mute': 2,
          'kind': '1',
          'regulars': [{'kind': '2',
            'maxval': '30',
            'minval': '1'}]}],
      'regulars': null,
    },
    {
      'id': '445245abb58e422ba48d1408c574e411',
      'text': 'E17.哪些方面的健康知识是您目前最想了解的？（请选出最需要的前3位 ）',
      'min': 3,
      'max': 3,
      'kind': '5',
      'code': 'E17',
      'order': 24,
      'remark': null,
      'options': [
        {
          'id': 'bc011445c8b1426f9b8b5e57b555d92a',
          'text': '①传染病防治（如流感、肝炎、艾滋病、结核病等） ',
          'jump': 0,
          'order': 1,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'b500d60504de4601b8d8e6b47cf58a72',
          'text': '②慢性病防治（如心脑血管疾病、糖尿病、癌症、慢性阻塞性肺病等）',
          'jump': 0,
          'order': 2,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '9961d2ffc3ed424e8715f042d37bf372',
          'text': '③科学就医、合理用药',
          'jump': 0,
          'order': 3,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '5953bad2f3b0441799c13f58a97d5c11',
          'text': '④合理营养、均衡膳食',
          'jump': 0,
          'order': 4,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'c324b0bdce024adebdd52cbd000b03ce',
          'text': '⑤科学运动',
          'jump': 0,
          'order': 5,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'db856f9615424028a892306a68290816',
          'text': '⑥健康危险因素预防',
          'jump': 0,
          'order': 6,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '5e0491f5d6f7464cbd84c14ff55c06a4',
          'text': '⑦心理健康',
          'jump': 0,
          'order': 7,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'f9bb4dfb1e624bfa8928ed2f01f3e880',
          'text': '⑧职业防护',
          'jump': 0,
          'order': 8,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': '6567829e53c04270be874cc231584576',
          'text': '⑨妇幼保健',
          'jump': 0,
          'order': 9,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'd014d2ba7e5341f58723c5013c8add60',
          'text': '⑩性与生殖健康',
          'jump': 0,
          'order': 10,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'c0c4956a2a054337b002770dce9bc5a0',
          'text': '⑪老年保健 ',
          'jump': 0,
          'order': 11,
          'mute': 2,
          'kind': '2',
          'regulars': null,
        },
        {
          'id': 'aa75492eae7f41dc993f0d28d1685381',
          'text': '12.其他{}_____             ',
          'jump': 0,
          'order': 12,
          'mute': 2,
          'kind': '1',
          'regulars': []}],
      'regulars': null}]}
